version: "3"

services:
  app:
    build: .
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - ./db_vol:/db
      - ./src:/app
      - ./config_vol:/config
    environment:
      PYTHONUNBUFFERED: 1
      RW_DB_PATH: /db/
      RW_CONFIG_PATH: /config/config.yaml

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=XXXXX
      - CONNECT=City
